version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: ./Dockerfile.postgres
    environment:
      POSTGRES_DB: bravo
      POSTGRES_PASSWORD: bravo_pass
      POSTGRES_USER: bravo

  redis:
        image: redis:latest
        volumes:
            - ./config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]

  app:
    build: .
    image: flima/bravo-ch:0.1
    ports:
      - 5678:8080
    depends_on:
      - postgres
      - redis

  cron:
    build:
      context: .
      dockerfile: ./Dockerfile.cron
    depends_on:
      - postgres
      - redis
